import 'package:flutter/material.dart' show BuildContext, ScaffoldMessenger, SnackBar, SnackBarBehavior, RoundedRectangleBorder, BorderRadius, Colors, Text;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/models.dart';
import 'security_log_service.dart';

/// Generates and shares institutional PDF reports for TradEt.
class PdfExportService {
  static final _cur = NumberFormat('#,##0.00', 'en');
  static final _pct = NumberFormat('0.00', 'en');

  // ─── Colours (matching TradEtTheme) ───
  static const _green = PdfColor.fromInt(0xFF4ADE80);
  static const _darkGreen = PdfColor.fromInt(0xFF0D3B20);
  static const _cardBg = PdfColor.fromInt(0xFF164D30);
  static const _textPrimary = PdfColor.fromInt(0xFFFFFFFF);
  static const _textSecondary = PdfColor.fromInt(0xFF6DAF87);
  static const _red = PdfColor.fromInt(0xFFEF4444);
  static const _amber = PdfColor.fromInt(0xFFF59E0B);

  // ─── CSMS Compliance Report ───────────────────────────────────────────
  static Future<void> exportCsmsReport({
    required BuildContext context,
    required User user,
    required List<PortfolioHolding> holdings,
    required List<SecurityLogEntry> events,
  }) async {
    final doc = pw.Document();
    final now = DateTime.now();
    final dateStr = DateFormat('dd MMMM yyyy').format(now);

    final shariaCompliant = holdings.where((h) => h.isShariaCompliant).length;
    final total = holdings.length;
    final shariaScore = total > 0 ? (shariaCompliant / total * 100) : 100.0;

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        theme: pw.ThemeData.withFont(
          base: await PdfGoogleFonts.nunitoRegular(),
          bold: await PdfGoogleFonts.nunitoBold(),
        ),
        header: (ctx) => _header(dateStr),
        footer: (ctx) => _footer(ctx),
        build: (ctx) => [
          _sectionTitle('CYBER SECURITY MANAGEMENT COMPLIANCE REPORT'),
          pw.SizedBox(height: 8),
          _infoRow('Audit Date', dateStr),
          _infoRow('Report Generated By', 'TradEt v1.0.0 — by Amber'),
          _infoRow('Standard', 'INSA CSMS Guideline v1.0 (CMCSRS + ISO/IEC 27000)'),
          pw.SizedBox(height: 20),

          // ── Section 1: User Identity & KYC ──────────────
          _sectionTitle('1. USER IDENTITY & KYC STATUS'),
          pw.SizedBox(height: 8),
          _infoRow('Full Name', user.fullName.isNotEmpty ? user.fullName : '—'),
          _infoRow('Email', user.email.isNotEmpty ? user.email : '—'),
          _infoRow('Account Type', user.accountType.toUpperCase()),
          _infoRow('KYC Status', user.kycStatus.toUpperCase(),
              valueColor: user.isKycVerified ? _green : _amber),
          _infoRow('KYC Tier', user.isKycVerified ? 'Tier 1 — Verified' : 'Pending Verification',
              valueColor: user.isKycVerified ? _green : _amber),
          pw.SizedBox(height: 20),

          // ── Section 2: Security Event Log ───────────────
          _sectionTitle('2. SECURITY EVENT LOG (LAST 30 EVENTS)'),
          pw.SizedBox(height: 8),
          if (events.isEmpty)
            pw.Text('No security events recorded.',
                style: pw.TextStyle(color: _textSecondary))
          else
            _eventTable(events.take(30).toList()),
          pw.SizedBox(height: 20),

          // ── Section 3: Sharia Compliance ────────────────
          _sectionTitle('3. SHARIA COMPLIANCE CERTIFICATE'),
          pw.SizedBox(height: 8),
          _infoRow('Standard Applied', 'AAOIFI Sharia Standards'),
          _infoRow('Screening Criteria',
              'Debt ratio < 30%  |  Haram revenue < 5%  |  No Riba instruments'),
          _infoRow('Total Holdings', '$total assets'),
          _infoRow('Sharia-Compliant Holdings', '$shariaCompliant / $total',
              valueColor: shariaScore >= 90 ? _green : _amber),
          _infoRow('Portfolio Compliance Score',
              '${_pct.format(shariaScore)}%',
              valueColor: shariaScore >= 90 ? _green : _amber),
          pw.SizedBox(height: 8),
          if (holdings.isNotEmpty) _holdingsTable(holdings),
          pw.SizedBox(height: 20),

          // ── Section 4: INSA Maturity Scorecard ──────────
          _sectionTitle('4. INSA MATURITY SCORECARD'),
          pw.SizedBox(height: 8),
          _scorecardTable(),
          pw.SizedBox(height: 20),

          // ── Certification statement ──────────────────────
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: _cardBg,
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'CERTIFICATION STATEMENT',
                  style: pw.TextStyle(
                      color: _green, fontWeight: pw.FontWeight.bold, fontSize: 11),
                ),
                pw.SizedBox(height: 6),
                pw.Text(
                  'This report certifies that TradEt v1.0.0 by Amber has implemented '
                  'security controls in accordance with the Ethiopian INSA Cyber Security '
                  'Audit & Evaluation Guideline v1.0. All financial instruments traded '
                  'through this platform are screened against AAOIFI Sharia standards. '
                  'Trading sessions are enforced per ECX official schedule. KYC/AML '
                  'requirements comply with NBE regulations.',
                  style: pw.TextStyle(color: _textPrimary, fontSize: 9, lineSpacing: 2),
                ),
              ],
            ),
          ),
        ],
      ),
    );

    final bytes = await doc.save();
    final filename = 'TradEt_CSMS_Report_${DateFormat('yyyyMMdd').format(now)}.pdf';

    if (context.mounted) {
      await Printing.sharePdf(bytes: bytes, filename: filename);
    }
  }

  // ─── Portfolio Statement PDF ──────────────────────────────────────────
  static Future<void> exportPortfolioStatement({
    required BuildContext context,
    required User user,
    required List<PortfolioHolding> holdings,
    required double cashBalance,
    required double totalValue,
  }) async {
    final doc = pw.Document();
    final now = DateTime.now();
    final dateStr = DateFormat('dd MMMM yyyy').format(now);

    final shariaCompliant = holdings.where((h) => h.isShariaCompliant).length;
    final shariaScore =
        holdings.isEmpty ? 100.0 : shariaCompliant / holdings.length * 100;

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        theme: pw.ThemeData.withFont(
          base: await PdfGoogleFonts.nunitoRegular(),
          bold: await PdfGoogleFonts.nunitoBold(),
        ),
        header: (ctx) => _header(dateStr),
        footer: (ctx) => _footer(ctx),
        build: (ctx) => [
          _sectionTitle('PORTFOLIO STATEMENT'),
          pw.SizedBox(height: 8),
          _infoRow('Client', user.fullName.isNotEmpty ? user.fullName : user.email),
          _infoRow('Statement Date', dateStr),
          _infoRow('KYC Status', user.kycStatus.toUpperCase(),
              valueColor: user.isKycVerified ? _green : _amber),
          _infoRow('Total Portfolio Value', 'ETB ${_cur.format(totalValue)}'),
          _infoRow('Cash Balance', 'ETB ${_cur.format(cashBalance)}'),
          _infoRow('Sharia Compliance Score',
              '${_pct.format(shariaScore)}% ($shariaCompliant / ${holdings.length} assets)',
              valueColor: shariaScore >= 90 ? _green : _amber),
          pw.SizedBox(height: 20),

          _sectionTitle('HOLDINGS'),
          pw.SizedBox(height: 8),
          if (holdings.isEmpty)
            pw.Text('No holdings.', style: pw.TextStyle(color: _textSecondary))
          else
            _holdingsTableFull(holdings),
          pw.SizedBox(height: 20),

          _complianceFooter(),
        ],
      ),
    );

    final bytes = await doc.save();
    final filename =
        'TradEt_Portfolio_${DateFormat('yyyyMMdd').format(now)}.pdf';
    if (context.mounted) {
      await Printing.sharePdf(bytes: bytes, filename: filename);
    }
  }

  // ─── Order History PDF ────────────────────────────────────────────────
  static Future<void> exportOrderHistory({
    required BuildContext context,
    required User user,
    required List<Order> orders,
  }) async {
    final doc = pw.Document();
    final now = DateTime.now();
    final dateStr = DateFormat('dd MMMM yyyy').format(now);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        theme: pw.ThemeData.withFont(
          base: await PdfGoogleFonts.nunitoRegular(),
          bold: await PdfGoogleFonts.nunitoBold(),
        ),
        header: (ctx) => _header(dateStr),
        footer: (ctx) => _footer(ctx),
        build: (ctx) => [
          _sectionTitle('ORDER HISTORY'),
          pw.SizedBox(height: 8),
          _infoRow('Client', user.fullName.isNotEmpty ? user.fullName : user.email),
          _infoRow('Statement Date', dateStr),
          _infoRow('Total Orders', '${orders.length}'),
          pw.SizedBox(height: 16),
          if (orders.isEmpty)
            pw.Text('No orders found.', style: pw.TextStyle(color: _textSecondary))
          else
            _ordersTable(orders),
          pw.SizedBox(height: 20),
          _complianceFooter(),
        ],
      ),
    );

    final bytes = await doc.save();
    final filename =
        'TradEt_Orders_${DateFormat('yyyyMMdd').format(now)}.pdf';
    if (context.mounted) {
      await Printing.sharePdf(bytes: bytes, filename: filename);
    }
  }

  // ─── Shared error snackbar ────────────────────────────────────────────
  static void showError(BuildContext context, Object e) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('PDF export failed: $e'),
        backgroundColor: Colors.redAccent,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
      ),
    );
  }

  // ─── PDF Widget Helpers ───────────────────────────────────────────────

  static pw.Widget _header(String dateStr) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 12),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: _green, width: 1.5)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('TradEt  |  ትሬድኢት',
                  style: pw.TextStyle(
                      color: _green,
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 16)),
              pw.Text('by Amber — Sharia-Compliant Ethiopian Trading',
                  style: pw.TextStyle(color: _textSecondary, fontSize: 9)),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text('CONFIDENTIAL',
                  style: pw.TextStyle(
                      color: _amber,
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 9)),
              pw.Text(dateStr,
                  style: pw.TextStyle(color: _textSecondary, fontSize: 9)),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _footer(pw.Context ctx) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: _cardBg, width: 0.5)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Sharia Board Compliance Certified — AAOIFI Standards Applied  |  '
            'ECX & NBE Compliant  |  INSA CSMS Guideline v1.0',
            style: pw.TextStyle(color: _textSecondary, fontSize: 7),
          ),
          pw.Text('Page ${ctx.pageNumber} / ${ctx.pagesCount}',
              style: pw.TextStyle(color: _textSecondary, fontSize: 7)),
        ],
      ),
    );
  }

  static pw.Widget _sectionTitle(String title) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      decoration: pw.BoxDecoration(
        color: _darkGreen,
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Text(title,
          style: pw.TextStyle(
              color: _green, fontWeight: pw.FontWeight.bold, fontSize: 11)),
    );
  }

  static pw.Widget _infoRow(String label, String value, {PdfColor? valueColor}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 180,
            child: pw.Text('$label:',
                style: pw.TextStyle(color: _textSecondary, fontSize: 10)),
          ),
          pw.Expanded(
            child: pw.Text(value,
                style: pw.TextStyle(
                    color: valueColor ?? _textPrimary,
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 10)),
          ),
        ],
      ),
    );
  }

  static pw.Widget _eventTable(List<SecurityLogEntry> events) {
    const headerStyle =
        pw.TextStyle(color: _green, fontSize: 9);
    final rowStyle = pw.TextStyle(color: _textPrimary, fontSize: 8);
    final subStyle = pw.TextStyle(color: _textSecondary, fontSize: 7);

    return pw.Table(
      border: pw.TableBorder.all(color: _cardBg, width: 0.5),
      columnWidths: const {
        0: pw.FlexColumnWidth(2.5),
        1: pw.FlexColumnWidth(3),
        2: pw.FlexColumnWidth(2),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _darkGreen),
          children: [
            _cell('Event', style: headerStyle),
            _cell('Timestamp', style: headerStyle),
            _cell('User', style: headerStyle),
          ],
        ),
        ...events.map((e) {
          // timestamp is ISO 8601 string; show first 19 chars
          final tsLabel = e.timestamp.length >= 19
              ? e.timestamp.substring(0, 19).replaceFirst('T', ' ')
              : e.timestamp;
          return pw.TableRow(children: [
            _cell(e.event, style: rowStyle),
            _cell(tsLabel, style: subStyle),
            _cell(
              e.userId.length > 12 ? '${e.userId.substring(0, 12)}…' : e.userId,
              style: subStyle,
            ),
          ]);
        }),
      ],
    );
  }

  static pw.Widget _holdingsTable(List<PortfolioHolding> holdings) {
    const headerStyle = pw.TextStyle(color: _green, fontSize: 9);
    final rowStyle = pw.TextStyle(color: _textPrimary, fontSize: 8);
    final compStyle = pw.TextStyle(color: _green, fontSize: 8);
    final ncStyle = pw.TextStyle(color: _amber, fontSize: 8);

    return pw.Table(
      border: pw.TableBorder.all(color: _cardBg, width: 0.5),
      columnWidths: const {
        0: pw.FlexColumnWidth(1.2),
        1: pw.FlexColumnWidth(2.5),
        2: pw.FlexColumnWidth(1.5),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _darkGreen),
          children: [
            _cell('Symbol', style: headerStyle),
            _cell('Asset Name', style: headerStyle),
            _cell('Sharia Status', style: headerStyle),
          ],
        ),
        ...holdings.map((h) => pw.TableRow(children: [
              _cell(h.symbol, style: rowStyle),
              _cell(h.assetName, style: rowStyle),
              _cell(
                h.isShariaCompliant ? 'COMPLIANT ✓' : 'NON-COMPLIANT',
                style: h.isShariaCompliant ? compStyle : ncStyle,
              ),
            ])),
      ],
    );
  }

  static pw.Widget _holdingsTableFull(List<PortfolioHolding> holdings) {
    const headerStyle = pw.TextStyle(color: _green, fontSize: 8);
    final rowStyle = pw.TextStyle(color: _textPrimary, fontSize: 8);

    return pw.Table(
      border: pw.TableBorder.all(color: _cardBg, width: 0.5),
      columnWidths: const {
        0: pw.FlexColumnWidth(1),
        1: pw.FlexColumnWidth(2),
        2: pw.FlexColumnWidth(1),
        3: pw.FlexColumnWidth(1.5),
        4: pw.FlexColumnWidth(1.5),
        5: pw.FlexColumnWidth(1.2),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _darkGreen),
          children: [
            _cell('Symbol', style: headerStyle),
            _cell('Name', style: headerStyle),
            _cell('Qty', style: headerStyle),
            _cell('Value (ETB)', style: headerStyle),
            _cell('P&L (ETB)', style: headerStyle),
            _cell('Sharia', style: headerStyle),
          ],
        ),
        ...holdings.map((h) => pw.TableRow(children: [
              _cell(h.symbol, style: rowStyle),
              _cell(h.assetName, style: rowStyle),
              _cell('${h.quantity} ${h.unit}', style: rowStyle),
              _cell(_cur.format(h.currentValue), style: rowStyle),
              _cell(
                '${h.pnl >= 0 ? '+' : ''}${_cur.format(h.pnl)}',
                style: pw.TextStyle(
                    color: h.pnl >= 0 ? _green : _red, fontSize: 8),
              ),
              _cell(
                h.isShariaCompliant ? '✓' : '✗',
                style: pw.TextStyle(
                    color: h.isShariaCompliant ? _green : _amber, fontSize: 8),
              ),
            ])),
      ],
    );
  }

  static pw.Widget _ordersTable(List<Order> orders) {
    const headerStyle = pw.TextStyle(color: _green, fontSize: 8);
    final rowStyle = pw.TextStyle(color: _textPrimary, fontSize: 8);

    return pw.Table(
      border: pw.TableBorder.all(color: _cardBg, width: 0.5),
      columnWidths: const {
        0: pw.FlexColumnWidth(1.5),
        1: pw.FlexColumnWidth(0.8),
        2: pw.FlexColumnWidth(1),
        3: pw.FlexColumnWidth(1.5),
        4: pw.FlexColumnWidth(1.5),
        5: pw.FlexColumnWidth(1),
        6: pw.FlexColumnWidth(1),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _darkGreen),
          children: [
            _cell('Date', style: headerStyle),
            _cell('Type', style: headerStyle),
            _cell('Symbol', style: headerStyle),
            _cell('Price (ETB)', style: headerStyle),
            _cell('Total (ETB)', style: headerStyle),
            _cell('Fee (ETB)', style: headerStyle),
            _cell('Status', style: headerStyle),
          ],
        ),
        ...orders.map((o) {
          final isBuy = o.orderType == 'buy';
          return pw.TableRow(children: [
            _cell(o.createdAt.length > 10 ? o.createdAt.substring(0, 10) : o.createdAt,
                style: rowStyle),
            _cell(
              o.orderType.toUpperCase(),
              style: pw.TextStyle(
                  color: isBuy ? _green : _red,
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 8),
            ),
            _cell(o.symbol, style: rowStyle),
            _cell(_cur.format(o.price), style: rowStyle),
            _cell(_cur.format(o.totalAmount), style: rowStyle),
            _cell(_cur.format(o.feeAmount), style: rowStyle),
            _cell(o.orderStatus.toUpperCase(), style: rowStyle),
          ]);
        }),
      ],
    );
  }

  static pw.Widget _scorecardTable() {
    const controls = [
      ['Authentication Controls', 'Account lockout (5 attempts/15 min), session timeout (10 min), password policy', 'IMPLEMENTED', true],
      ['Audit Trail / Logging', 'SecurityLogService — append-only chained hash log, 12 event types', 'IMPLEMENTED', true],
      ['Data Confidentiality', 'Balance masking (eye toggle), account number masking (last 4 digits)', 'IMPLEMENTED', true],
      ['Privacy & Consent', 'ToS/Privacy Policy checkbox required at registration', 'IMPLEMENTED', true],
      ['Access Control (KYC Gate)', 'Trade blocked for unverified users — NBE KYC requirement', 'IMPLEMENTED', true],
      ['ECX Session Enforcement', 'Buy/Sell disabled outside official ECX trading session hours', 'IMPLEMENTED', true],
      ['Sharia Screening', 'AAOIFI thresholds (debt <30%, haram revenue <5%) on all assets', 'IMPLEMENTED', true],
      ['App Lock / Biometric', 'PIN/biometric re-authentication after 60s background', 'PLANNED', false],
      ['Encryption at Rest', 'Sensitive tokens in flutter_secure_storage (planned)', 'PLANNED', false],
    ];

    const headerStyle = pw.TextStyle(color: _green, fontSize: 9);
    final labelStyle = pw.TextStyle(color: _textPrimary, fontSize: 8);
    final descStyle = pw.TextStyle(color: _textSecondary, fontSize: 7);

    return pw.Table(
      border: pw.TableBorder.all(color: _cardBg, width: 0.5),
      columnWidths: const {
        0: pw.FlexColumnWidth(2),
        1: pw.FlexColumnWidth(4),
        2: pw.FlexColumnWidth(1.2),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _darkGreen),
          children: [
            _cell('Control', style: headerStyle),
            _cell('Implementation', style: headerStyle),
            _cell('Status', style: headerStyle),
          ],
        ),
        ...controls.map((c) {
          final implemented = c[3] as bool;
          return pw.TableRow(children: [
            _cell(c[0] as String, style: labelStyle),
            _cell(c[1] as String, style: descStyle),
            _cell(
              implemented ? '✓ DONE' : '○ PLANNED',
              style: pw.TextStyle(
                  color: implemented ? _green : _amber,
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 8),
            ),
          ]);
        }),
      ],
    );
  }

  static pw.Widget _complianceFooter() {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: _darkGreen,
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Text(
        'Sharia Board Compliance Certified — AAOIFI Standards Applied  |  '
        'ECX & NBE Compliant  |  No Riba (interest) instruments  |  '
        'INSA CSMS Guideline v1.0 — Target Maturity: Mature (76–90)',
        style: pw.TextStyle(color: _textSecondary, fontSize: 8),
        textAlign: pw.TextAlign.center,
      ),
    );
  }

  static pw.Widget _cell(String text, {pw.TextStyle? style}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
      child: pw.Text(text, style: style),
    );
  }
}
